"""Generate docs/RESULTS.md from results/*.json. Do not edit RESULTS.md by hand."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / "results"
tests = json.loads((R / "tests.json").read_text())
audit = json.loads((R / "audit.json").read_text())
bench = json.loads((R / "bench_yaro_1105.json").read_text())
cpu = (R / "bench_cpu.txt").read_text().strip()
pins = dict(line.split() for line in (ROOT / "models" / "PINNED_COMMITS.txt").read_text().splitlines())

L = ["# Results", "",
     "Generated by `python3 scripts/make_report.py` from `results/*.json`. Do not edit by hand.",
     "Descriptions: YardStick Robotics' public `yaro_*_description` repositories (MIT) at the commits in `models/PINNED_COMMITS.txt`.",
     "Data sheet values: `models/datasheet.txt` (YARO Cobot data sheet, retrieved 2026-09-26).", ""]

L += ["## Tests", "", f"**{tests['total']} test cases, {tests['failures']} failures** (`make test`, ROS 2 Jazzy in Docker).", "",
      "| suite | cases | failures |", "|---|---|---|"]
for s in tests["suites"]:
    L.append(f"| {s['file'].replace('.gtest.xml', '').replace('.xunit.xml', '')} | {s['tests']} | {s['failures']} |")
kdl = next(s for s in tests["suites"] if s["file"].startswith("test_kdl_crosscheck"))
worst = {k: max(v[k] for v in kdl["properties"].values()) for k in ("worst_position_error_m", "worst_rotation_error", "worst_jacobian_error")}
L += ["", "KDL cross-check, 1000 random configurations per model, worst case over all five models: "
      f"position {worst['worst_position_error_m']:.1e} m, rotation matrix entry {worst['worst_rotation_error']:.1e}, "
      f"Jacobian entry {worst['worst_jacobian_error']:.1e} (test threshold 1e-12).", ""]

L += ["## Model audit", "", "| model | commit | links | actuated | URDF mass (kg) | data sheet weight (kg) | sampled reach (mm) | data sheet reach (mm) | errors | warnings |",
      "|---|---|---|---|---|---|---|---|---|---|"]
for m in audit["models"]:
    ds = m["datasheet"] or {}
    L.append(f"| {m['model']} | `{pins[m['model']][:7]}` | {m['links']} | {m['actuated']} | {m['total_mass_kg']:.2f} | {ds.get('weight_kg', '-')} | "
             f"{m['sampled_horizontal_reach_mm']:.0f} | {ds.get('reach_mm', '-')} | {m['errors']} | {m['warnings']} |")
L += ["", f"Reach = largest horizontal distance of `ee_frame` from the A1 axis over {audit['reach_samples']:,} random joint "
      f"configurations inside the URDF limits (seed {audit['seed']}), so it is a lower bound of the true maximum. "
      "The data sheet does not define its reach reference point.", ""]
rules = {}
for m in audit["models"]:
    for f in m["findings"]:
        rules.setdefault((f["rule"], f["error"]), set()).add(m["model"])
L += ["Findings (same on every model):", ""]
for (rule, err), models in sorted(rules.items()):
    n = sum(1 for m in audit["models"] for f in m["findings"] if f["rule"] == rule) // len(models)
    L.append(f"- `{rule}` ({'error' if err else 'warning'}): {n} per model, on {len(models)} of {len(audit['models'])} models")
L += [""]

L += ["## URDF limits vs data sheet", "",
      "Symmetric working range (half range, deg) and maximum speed (deg/s) per axis. `urdf / data sheet`; bold = differs by more than 0.5.", "",
      "| model | " + " | ".join(f"A{i} range" for i in range(1, 7)) + " | " + " | ".join(f"A{i} speed" for i in range(1, 7)) + " |",
      "|---|" + "---|" * 12]
for m in audit["models"]:
    cells = {("range", i): "" for i in range(6)}
    for c in m["comparisons"]:
        i = int(c["joint"].split("_")[1]) - 1
        txt = f"{c['urdf']:.0f} / {c['datasheet']:.0f}"
        cells[(c["quantity"], i)] = txt if c["matches"] else f"**{txt}**"
    L.append(f"| {m['model']} | " + " | ".join(cells[("range", i)] for i in range(6)) + " | "
             + " | ".join(cells[("speed", i)] for i in range(6)) + " |")
n_mis = sum(1 for m in audit["models"] for c in m["comparisons"] if not c["matches"])
n_all = sum(len(m["comparisons"]) for m in audit["models"])
L += ["", f"{n_mis} of {n_all} values differ. The data sheet may describe certified or derated limits and the URDF "
      "the drive limits, or the other way round; which one a controller should enforce is a question for the robot's owners, "
      "not something this check can decide.", ""]

L += ["## Kinematics speed", "", f"`yaro_bench` on yaro_1105, single thread, {bench['calls']:,} calls x {bench['repeats']} repeats, median; CPU: {cpu} (Docker).", "",
      "| | yaro_check | KDL | speed-up |", "|---|---|---|---|",
      f"| forward kinematics (ns/call) | {bench['fk_ns']:.0f} | {bench['fk_kdl_ns']:.0f} | {bench['fk_kdl_ns'] / bench['fk_ns']:.1f}x |",
      f"| Jacobian (ns/call) | {bench['jacobian_ns']:.0f} | {bench['jacobian_kdl_ns']:.0f} | {bench['jacobian_kdl_ns'] / bench['jacobian_ns']:.1f}x |", ""]

(ROOT / "docs" / "RESULTS.md").write_text("\n".join(L))
print("wrote docs/RESULTS.md")
